list_unable = [
  "So Baby (From \"Doctor\")",
  "Vaadi Pulla Vaadi - From \"Meesaya Murukku\"",
  "Yaanji - From \"Vikram Vedha\"",
  "Un Paarvayil",
  "Orasaadha - Madras Gig",
  "Single Pasanga - From \"Natpe Thunai\"",
  "Kaattu Payale",
  "Bae (From \"Don\")",
  "Unnaalae",
  "Adi Penne",
  "Kaadhal Vaithu",
  "Adada Adada",
  "Hi Sonna Pothum (From \"Comali\")",
  "Paisa Note (From \"Comali\")",
  "Kadhalikathey - From \"Imaikkaa Nodigal\"",
  "Pudichiruka Illa Pudikalaya - From \"Kalakalappu 2\"",
  "Karakudi Ilavarasi - From \"Kalakalappu 2\"",
  "Thanimai Kadhal",
  "Shades of Kadhal",
  "Enakenna Yaarum Illaye (From \"Aakko\")",
  "Ale Ale",
  "Aagaayam",
  "Mai Potta Kannala",
  "Oru Manam (From \"Dhruva Natchathiram\")",
  "Kannamma - From \"Ispade Rajavum Idhaya Raniyum\"",
  "Sol Sol",
  "Ale Ale",
  "Private Party (From \"Don\")",
  "Un Aruginil Yeno (Original Soundtrack)",
  "Adipoli (From \"Think Originals\")",
  "Kadhal Psycho (From \"Saaho\")",
  "Unmai Edhu Poy Edhu (From \"Saaho\")",
  "Megham Karukatha (From \"Thiruchitrambalam\")",
  "Pogiren",
  "Kambathu Ponnu",
  "Otha Thamarai - Original Soundtrack",
  "Thenmozhi (From \"Thiruchitrambalam\")",
  "Sahana Saral Thoo", ##
  "Kannave Kannave - From \"Sketch\"",
  "Jessica",
  "Ennai Vittu (From \"Love Today\")",
  "Kaadhal En Kaviye - From \"Salmon 3D\"",
  "Kannmoodi Thirakkum",
  "Engeyum Kaadhal",
  "Mudhal Nee Mudivum Nee Title Track (From \"Mudhal Nee Mudivum Nee\")",
  "Saachitale (From \"Love Today\")",
  "Kadhaippoma",
  "Arabic Kuthu - Halamithi Habibo (From \"Beast\")",
  "Poopol Poopol",
  "Adiyae Azhagae - From \"Oru Naal Koothu\"",
  "Azhage (feat. Thenuja)",
  "Raati - Madras Gig",
  "Idhuvum Kadandhu Pogum (The Healing Song) (From \"Netrikann\")",
  "Aradhya (From \"Kushi\") (Tamil)",
  "Thimiru Kaattaadha Di - From \"LKG\"",
  "Tamil Tamil",
  "En Rojaa Neeye"
]

print(len(list_unable))